feat: 디바운싱 기능 추가
LuckyBicky-Team/Outsourcing-project pull request #7
Opened 2024-06-18 12:04 UTC by host2024

1, 파일 명 수정 

2, 디바운싱 기능 추가

2024-06-18 12:13 UTC, 1eeyerin requested changes
👍 최고 운성님 수고 많으십니댜! 요고 한번 확인 부탁드릴게요!

2024-06-18 12:13 UTC, 1eeyerin commented on src/components/StoreContainer.jsx
> +      clearTimeout(debounceTimeout.current);
혹시 clearTimeout을 입력값이 바뀔때마다 계속 취소하는 이유가 있으신지 궁금합니다!
컴포넌트 언마운트시에 한번 실행시키는 것을 의도하시는 것일까요?

2024-06-18 12:13 UTC, 1eeyerin commented on src/components/StoreContainer.jsx
> +  padding: 56px 0;
개행 부탁드려요~

2024-06-18 12:13 UTC, 1eeyerin commented on src/components/StoreContainer.jsx
> +  h2 {
혹시 이 안에 스타일을 종속시켜야하는 이유가 있으실까요?
wrapper 안에 모든 h2에 변경시키는 것이 의도된 동작인지 궁금합니다!
되도록이면 모두 스타일드 컴포넌트로 따로 분리해서 1depth를 유지하였으면 좋겠습니다~

2024-06-18 12:13 UTC, 1eeyerin commented on src/components/StoreContainer.jsx
> +  background-color: #fff;
컬러는 6자리로 통일해주세요~
나중에 white를 수정하려는 경우에 #fff , #ffffff #FFF, #FFFFFF, white, 255,255,255를 전부 찾아야하는 어려움이 있으니 되도록이면 컬러의 사용방식을 통일시켜주셨으면 좋겠습니다!

2024-06-18 12:13 UTC, 1eeyerin commented on src/components/StoreContainer.jsx
> +  form {
안에 종속된 태그 전부 따로 분리 부탁드립니다~

2024-06-18 12:13 UTC, 1eeyerin commented on src/components/StoreContainer.jsx
> +  overflow-y: auto;
개행 부탁드립니다~

2024-06-18 12:13 UTC, 1eeyerin commented on src/pages/Store/Store.jsx
> +    <div>
div가 꼭 필요한 상황인지 궁금합니다~!

2024-06-18 12:23 UTC, host2024 commented on src/components/StoreContainer.jsx
> +      clearTimeout(debounceTimeout.current);
그 부분을 추가한 이유는 useEffect에 디펜더시쪽에 searchTerm으로 검색이 되게 해서 없다면 쓸 때 마다 팝업창이 뜨게 되는 오류가 있습니다

2024-06-18 12:31 UTC, host2024 commented on src/components/StoreContainer.jsx
> +  padding: 56px 0;
수정했습니다!

2024-06-18 12:36 UTC, host2024 commented on src/pages/Store/Store.jsx
> +    <div>
제거 하는 걸 까먹었네요 바로 수정했습니다

2024-06-18 12:52 UTC, jeoninhwa3 commented on src/components/StoreContainer.jsx
> +  h2 {
스타일 컴포넌트가 많아져서 네이밍이 어려워 종속 시켰습니다 ㅎㅎ
1depth로 분리하는게 가독성에 좋을까요?

2024-06-18 12:53 UTC, host2024 commented on src/components/StoreContainer.jsx
> +  form {
네 분리 완료 했습니다!

2024-06-18 12:57 UTC, host2024 commented on src/components/StoreContainer.jsx
> +  background-color: #fff;
수정 완료 했습니다

2024-06-18 12:59 UTC, host2024 commented on src/components/StoreContainer.jsx
> +  overflow-y: auto;
완료 했습니다!

2024-06-18 13:14 UTC, host2024 commented on src/components/StoreContainer.jsx
> +  h2 {
수정 했습니다!

2024-06-18 13:49 UTC, host2024 commented on src/components/StoreContainer.jsx
> +      clearTimeout(debounceTimeout.current);
수정 했습니다

2024-06-19 03:35 UTC, 1eeyerin approved these changes
수고 많으셨습니다 운성님!! 👍

2024-06-19 03:39 UTC, merged